### ISSUE TITLE
docker_run.sh crashes  out if pid files exist

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#108]
If the pid files exist `docker_run.sh` doesn't delete them, but crashes out, taking any existing process with it (because it tries to kill the processes, and that seems to cause the container to exit). That also happens with `--shell`,  so running `doker_run.sh --shell` currently causes the prod instance to crash.

**Comment by mjzffr** [comment]
`run_docker.sh run` calls the docker entrypoint script, `start_wptsync.sh` so the rest of my reply is about `start_wptsync.sh`.

* First, the calls to `cleanup` should be moved to the `[ "$1" == "--worker" ]` if-clause, since that's the only case in which the script starts celery and celery beat.
* The pid files are in the `workspace` directory, which is shared by the host and all containers. We could change the location of the pid files to be in local container storage to allow many containers to run celery at once. If we run two sync services at once, they share all the same data under `workspace` and `repos` by default, but they can't stomp over each other because of `sync.lock` so that should be fine. We've run wptsync commands while the main sync service was running, and that was fine, but there is only one instance of celery running in that case. [@jgraham Can you think of a reason to prevent running many sync services (with independent celery processes) at once?]  

If we decide that running many independent celeries at once is bad and therefore we leave the pid files in `workspace`, I would just have `start_wptsync.sh` abort celery/sync-service start-up if any shared pid file is found and leave the pid-cleanup decision up to a human. ("Celery is already running in another container. If you want to start a new celery instance, stop the other process and try again.")

**Comment by mjzffr** [comment]
> That also happens with --shell, so running doker_run.sh --shell currently causes the prod instance to crash.

@jgraham I can't reproduce this. I just ran `run_docker.sh run --shell` and the prod instance was unaffected.

`run_docker.sh` stops at `kill -0 some_pid` because that returns non-zero exit status (due to that pid not being associated with any process in the new container) but it doesn't do anything else. This is kind of a lucky bug (I need to add `set +e`, `set -e` around it to actually delete the pid) in that it's made me realize that this won't work well when starting multiple containers (see my previous comment).
