### ISSUE TITLE
wpt-sync of a reftest runs an excessive number of Linux debug jobs

### ISSUE THREAD

**Issue by dbaron** [mozilla/wpt-sync#27]
wpt-sync of a reftest runs an excessive number of Linux debug jobs, apparently since the normal wpt runs on Linux debug are split into 6 parts, and the sync run looks like it replaces *each* part with a run of the new tests.  See, for example, [this try run](https://treeherder.mozilla.org/#/jobs?repo=try&revision=3c1363d167f401fc0a62b20359a24fd012f92176) for the sync in [bug 1438361](https://bugzilla.mozilla.org/show_bug.cgi?id=1438361) (which was for a PR I made directly to w-p-t).

**Comment by jgraham** [comment]
This is a bug in the way we construct  the try push that sems from the limitations of try syntax; because reftests are sometimes chunked and sometimes not we can't (using try syntax) specify to run -reftests-1 on the platforms  where it is chunked and -reftests on the platforms where it is not. @mjzffr do we have the ability to solve this before we switch to the fuzzy try syntax everywhere?

**Comment by jgraham** [comment]
This will be fixed when we implement the proposal in #28

**Comment by jgraham** [comment]
https://github.com/mozilla/wpt-sync/commit/14424d3be8468a0628140130bb7c13e033718d34#diff-ecbd794a18148944cd3850c126a62c5b should fix this by moving to `mach try fuzzy`.
