### ISSUE TITLE
Don't try to reland upstream PRs if the commits didn't change

### ISSUE THREAD

**Issue by jgraham** [mozilla/wpt-sync#379]
When we upstream a change from gecko to wpt and then try to update the gecko sync point past that PR we try to reapply the changes from the PR in case someone pushed additional changes not present in the gecko branch. But in the common case where this doesn't happen we should be able to tell because the head of the PR will be the same as the last commit that the sync pushed. In this case we should be able to skip relanding the PR altogether. This will also allow us to remove the current hack where we skip in cases that the files in GitHub and m-c look identical.

**Comment by dhdavvie** [comment]
Would this be fixed by checking the commit hashes in [gecko_push](https://github.com/mozilla/wpt-sync/blob/master/sync/upstream.py#L810)? Something along the lines of:

```py
if rev == last_sync_point.commit.sha1:
    logger.info("Last sync point is the same as this revision")
    return
```

And place this right before the lock? Or as an elif to the [ancestor check](https://github.com/mozilla/wpt-sync/blob/master/sync/upstream.py#L816)?
